---
title: "Analysis of morphine behavioural data"
author: "Ben Barry"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load libraries
```{r load libraries}
library(tidyverse) #data wrangling plotting ect.. 
library(here)
library(wesanderson)  #colour pallets
library(gt) #formating tables
library(lme4)
library(emmeans) # posthoc for lMM
library(sjPlot)
library(car)
library(xtable)
```

```{r}
## generate a colour pallet for plotting 
pal <- wes_palette("Zissou1", 5, type = "discrete")
pal_cont <- wes_palette("Zissou1", 21,  type = "continuous")

```


#load data
```{r}
rawMorphineData <- read_csv("../data/raw_morphine_data.csv")

animalInfo <- read_csv("../data/animals.csv")
```

# rename ID column
```{r}
#colnames for raw morphine data are strange becuase of the CSV. 
# I will rename the first to ID. 
rawMorphineData =rename(rawMorphineData, ID = ...1)

```

#write a row of stats function.
```{r}
row_of_stats = function(row, timepoint) {
  mean_val <- mean(row)
  sd_val <- sd(row)
  n_val <- sum(!is.na(row))
  return(c(mean = mean_val, sd = sd_val, n = n_val, timepoint = timepoint))
}
```
#finding the means of the data.
```{r}
# make a table for each of the timepoints
# this is a little messy and but 

baselineStats = apply(rawMorphineData[, 2:4], 1, row_of_stats, timepoint = 0)

stats30 <- apply(rawMorphineData[, 5:7], 1, row_of_stats, timepoint = 30)

stats60 <- apply(rawMorphineData[, 8:10], 1, row_of_stats, timepoint = 60)

rawStats <- t(cbind(baselineStats, stats30 , stats60))

```

# editing the ainmalInfo Table
```{r editing info data}
animalInfo <- animalInfo %>%
  rename(treatment = Saline,
         genotype = phenotype,
         sex = Sex) %>%
replace_na(list(treatment = "morphine")) %>%
  mutate(treatment = if_else(treatment == "x", "saline", treatment)) %>%
  select(ID, sex, genotype, treatment)

morphineData <- cbind(animalInfo, rawStats)


           
```

#plotting raw data
```{r ploting raw data}
## morphine  dot plot 
morphine_dot_plot <- ggplot(morphineData,
       aes(x = factor(timepoint),
           y = mean,
           fill = interaction(sex, genotype))) +
  geom_point(position = position_jitter(width = 0.1, height = 0),
             size = 3, 
             shape = 21,
             colour = "black") +
  stat_summary(fun = mean, geom = "line",
              aes(group = interaction(sex, genotype),
                  colour = interaction(sex, genotype)),
                  show.legend = FALSE) +
  labs(x = "Timepoint",
       y = "withdrawal latency (s)",
       fill = "Group") +
  theme_classic() +
  scale_fill_manual(values = pal,
                      labels = c("f.WT" = "WT female",
                                 "f.A20" = "I325N female",
                                 "m.WT" = "WT male",
                                 "m.A20" = "I325N male")) +
  scale_colour_manual(values = pal) +
  facet_grid(~ treatment)

morphine_dot_plot #show plot

#bar plots comparing treatments
male_morphine_genotype_interaction <- ggplot(subset(morphineData, sex == "m"), 
       aes(x = factor(timepoint),
           y = mean,
           fill = treatment)) +
  geom_boxplot(colour = "black") +
  facet_grid(~ genotype) +
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00")) + 
  theme_classic()  +
  geom_jitter(aes(y= mean),
              shape = 21,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "Male genotype interaction",
       x = "timepoint",
       y = "withdrawal latency (s)") +
  ylim(c(0, 20))

male_morphine_genotype_interaction #show plot

#barlpot of female results
female_morphine_genotype_interaction <- ggplot(subset(morphineData, sex == "f"), 
       aes(x = factor(timepoint),
           y = mean,
           fill = treatment)) +
  geom_boxplot(colour = "black") +
  facet_grid(~ genotype) +
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00")) + 
  theme_classic()  +
  geom_jitter(aes(y= mean),
              shape = 21,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "Female genotype interaction",
       x = "timepoint",
       y = "withdrawal latency (s)") +
  ylim(c(0, 20))
female_morphine_genotype_interaction #show plot

ggsave("female_morphine_genotype_interaction.png", female_morphine_genotype_interaction, width = 6, height = 4, path = "../figures")

ggsave("male_morphine_genotype_interaction.png", male_morphine_genotype_interaction, width = 6, height = 4, path = "../figures")

ggsave("morphine_dot_plot.png", morphine_dot_plot, width = 6, height = 4, path = "../figures")
```
#calculating MPE 
```{r calculating mpe}
morphineMPEdata <- morphineData %>%
  select(ID, genotype, sex, timepoint, mean, treatment) %>%
  pivot_wider(names_from = timepoint, values_from = mean)%>%
  mutate(mpe30 = (`30` - `0`) / (18 - `0`) * 100,
         mpe60 = (`60` - `0`) / (18 - `0`) * 100)
```

#comparing MPE or morphine to saline.
```{r ploting mpe}
ggplot(subset(morphineMPEdata, sex == "m"), 
       aes(x = treatment,
           y = mpe30,
           fill = treatment)) +
  geom_bar(stat = "summary",
           position = position_dodge(),
           colour = "black") +
  facet_grid(~ genotype) +
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00")) + 
  theme_classic()  +
  geom_jitter(aes(y= mpe30),
              shape = 21,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "Male morphine effect",
       x = "timepoint",
       y = "mpe")

ggplot(subset(morphineMPEdata, sex == "f"), 
       aes(x = treatment,
           y = mpe30,
           fill = treatment)) +
  geom_bar(stat = "summary",
           position = position_dodge(),
           colour = "black") +
  facet_grid(~ genotype) +
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00")) + 
  theme_classic()  +
  geom_jitter(aes(y= mpe30),
              shape = 21,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "Female morphine effect",
       x = "timepoint",
       y = "mpe")

```

#comparing morphine mpe by timepoint. 
```{r plotting mpe}
MPE_30min <- ggplot(subset(morphineMPEdata, treatment == "morphine"), 
       aes(x = interaction(treatment, genotype),
           y = mpe30,
           fill = interaction(treatment, genotype))) +
  geom_bar(stat = "summary",
           position = position_dodge(),
           colour = "black") +
  scale_x_discrete(labels = c("morphine.A20" = "I325N",
                              "morphine.WT" = "WT")) +
  facet_grid(~ sex,
             labeller = as_labeller(c("f" = "Female",
                                      "m" = "Male")))+
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00"),
       guide = "none") + 
  theme_classic()  +
  geom_jitter(aes(y= mpe30),
              shape = 21,   
              size = 3,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "maximum potential effect of morphine at 30m",
       x = "genotype",
       y = "MPE")+
  ylim(c(0, 100))
MPE_30min 

MPE_60min <- ggplot(subset(morphineMPEdata, treatment == "morphine"), 
       aes(x = interaction(treatment, genotype),
           y = mpe60,
           fill = interaction(treatment, genotype))) +
  geom_bar(stat = "summary",
           position = position_dodge(),
           colour = "black") +
  scale_x_discrete(labels = c("morphine.A20" = "I325N",
                              "morphine.WT" = "WT")) +
  facet_grid(~ sex,
             labeller = as_labeller(c("f" = "Female",
                                      "m" = "Male"))) +
  scale_fill_manual(values = c("#3B9AB2", "#E1AF00"),
       guide = "none") + 
  theme_classic()  +
  geom_jitter(aes(y= mpe60),
              shape = 21,
              size = 3,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1,)) +
  labs(title = "maximum potential effect of morphine at 60m",
       x = "genotype",
       y = "MPE") +
  ylim(c(0, 100))
MPE_60min 







ggsave("MPE_30min.png", MPE_30min, width = 6, height = 4, path = "../figures")
ggsave("MPE_60min.png", MPE_60min, width = 6, height = 4, path = "../figures")

```


```{r long format of MPE data}
morphineMPE <- morphineMPEdata %>%
  select(- c(`0`, `30`, `60`)) %>%
  filter(treatment == "morphine") %>%
  pivot_longer(cols = 5:6,
               names_to = "timepoint",
               values_to = "mpe") %>%
  mutate(timepoint = str_extract(timepoint, "(30|60)")) %>%
  ggplot(aes(factor(timepoint),
             mpe,
             fill = interaction (sex, genotype)
             )) +
  geom_point(position = position_jitter(width = 0.1, height = 0),
             size = 3, 
             shape = 21,
             colour = "black") +
  stat_summary(fun = mean, geom = "line",
              aes(group = interaction(sex, genotype),
                  colour = interaction(sex, genotype)),
                  show.legend = FALSE) + 
  theme_classic() +
  scale_fill_manual(values = pal,
                    labels = c("f.WT" = "WT female",
                                 "f.A20" = "I325N female",
                                 "m.WT" = "WT male",
                                 "m.A20" = "I325N male")) +
  scale_colour_manual(values = pal) + 
  labs(x = "Timepoint",
       y = "maximum potential effect of morphine",
       fill = "Group")

morphineMPE
ggsave("morphineMPE.png", morphineMPE, width = 6, height = 4, path = "../figures")


```

#satistical anlysis on MPE data.
```{r satistics on mpe data}
# an important assumption of anova is the the data is normally distributed in all groups. 

#this is for mpe30 data

# test on all mpe30 data.
morphineMPEdata %>%
  filter(treatment == "morphine") %>%
  select(mpe30) %>%
  pull() %>%
  shapiro.test()

#test on wt males
morphineMPEdata %>%
  filter(treatment == "morphine",
         genotype == "WT",
         sex == "m") %>%
  select(mpe30) %>%
  pull() %>%
  shapiro.test()

#test on a20 males
morphineMPEdata %>%
  filter(treatment == "morphine",
         genotype == "A20",
         sex == "m") %>%
  select(mpe30) %>%
  pull() %>%
  shapiro.test()

#test on wt Females
morphineMPEdata %>%
  filter(treatment == "morphine",
         genotype == "WT",
         sex == "f") %>%
  select(mpe30) %>%
  pull() %>%
  shapiro.test()

#test on a20 Females
morphineMPEdata %>%
  filter(treatment == "morphine",
         genotype == "A20",
         sex == "f") %>%
  select(mpe30) %>%
  pull() %>%
  shapiro.test()
# most of the data is normally distbiuted
# we can also test the normality of the residuals. 
```


```{r normality testing on the residuals}

#analysis of mpE AT 30 minutes.
#test normality on residuals
mpe30AOV <- morphineMPEdata %>%
  filter(treatment == "morphine") %>%
  aov(mpe30 ~ sex * genotype, .)

#test residuals
shapiro.test(mpe30AOV$residuals)

#since assumptions are met get ANOVA summary
summary(mpe30AOV)

#since there is a significant interaction perform posthoc
TukeyHSD(mpe30AOV)


#analysis of mpE AT 60 minutes.
#test normality on residuals
mpe60AOV <- morphineMPEdata %>%
  filter(treatment == "morphine") %>%
  aov(mpe60 ~ sex * genotype, .)

#test residuals
shapiro.test(mpe60AOV$residuals)

#since assumptions are met get ANOVA summary
summary(mpe60AOV)

#since there is a significant interaction perform posthoc
TukeyHSD(mpe60AOV)
```

#linear mixed effects on the delta
```{r finding the delta between timpoint and treatment}

morphineDelta <- morphineData %>%
  group_by(ID, timepoint, sex, genotype) %>%
  summarise(delta = 
    mean[treatment=="morphine"] - mean[treatment == "saline"]) %>%
  ungroup()

morphineDeltaBoxplot <- morphineDelta %>%
  ggplot(aes(
    x = interaction(sex, genotype),
    y = delta,
    fill = interaction(sex, genotype)
  )) + 
  geom_boxplot() + 
  facet_grid(~ timepoint) +
  scale_fill_manual(values = pal,
                    labels = c("f.WT" = "WT female",
                                 "f.A20" = "I325N female",
                                 "m.WT" = "WT male",
                                 "m.A20" = "I325N male")) + 
  theme_classic()  +
  geom_jitter(aes(y= delta),
              shape = 21,
              position = position_jitterdodge(dodge.width = 0.9,
                                              jitter.width = 0.1)) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
        ) + 
  labs(x = "Group by time",
       y = "Withdrawal latency normalised to saline (s)",
       fill = "Group")
morphineDeltaBoxplot


morphineDelta_dotplot <- morphineDelta %>%
  ggplot(aes(factor(timepoint),
             delta,
             fill = interaction (sex, genotype)
             )) +
  geom_point(position = position_jitter(width = 0.1, height = 0),
             size = 3, 
             shape = 21,
             colour = "black") +
  stat_summary(fun = mean, geom = "line",
              aes(group = interaction(sex, genotype),
                  colour = interaction(sex, genotype)),
                  show.legend = FALSE) + 
  theme_classic() +
  scale_fill_manual(values = pal,
                    labels = c("f.WT" = "WT female",
                                 "f.A20" = "I325N female",
                                 "m.WT" = "WT male",
                                 "m.A20" = "I325N male")) +
  scale_colour_manual(values = pal) + 
  labs(x = "Timepoint",
       y = "Withdrawal latency normalised to saline (s)",
       fill = "Group")
morphineDelta_dotplot  

ggsave("morphineDelta_dotplot.png", morphineDelta_dotplot, width = 6, height = 4, path = "../figures")
  

#model for the analysis of varience.
deltaAOV <- aov(delta ~ sex * genotype * factor(timepoint), data = morphineDelta)
shapiro.test(deltaAOV$residuals)
summary(deltaAOV)

#linear mixed effects modelling. 
delta_mixed_effect1<- lmer(sqrt(delta + 1) ~ factor(timepoint) * sex * genotype + (1|ID), data = morphineDelta)
plot(delta_mixed_effect1)
hist(resid(delta_mixed_effect1))
summary(delta_mixed_effect1)
Anova(delta_mixed_effect1)
emmeans(delta_mixed_effect1, pairwise ~ sex*genotype|timepoint)


```


#linear mixed effects on all data
```{r linear mixed effect of data}

morphineLMEfourWay <- lmer(log(mean) ~  factor(timepoint) * genotype * sex * treatment + (1|ID), data = morphineData)

morphineLMEthreeWay <- lmer(log(mean) ~  (factor(timepoint) + genotype + sex + treatment)^3 + (1|ID), data = morphineData)
                            
                            
summary(morphineLMEfourWay)
plot(morphineLMEfourWay)
hist(resid(morphineLMEfourWay))
qqnorm(resid(morphineLMEfourWay))
qqline(resid(morphineLMEfourWay))
Anova(morphineLMEfourWay)
hist(log(morphineData$mean))

tab_model(morphineLMEthreeWay)
morphineLMEemmeans <- emmeans(morphineLMEfourWay, pairwise ~ sex * genotype|treatment * (factor(timepoint)))
print(morphineLMEemmeans)

#plot the model on the data
predictMorphineLME <- predict(morphineLME)

predictMorphineLME_model <- morphineData %>%
  na.omit() %>%
  cbind(predictMorphineLME) %>%
  mutate(timepoint = factor(timepoint))

ggplot(predictMorphineLME_model, aes(x = factor(timepoint),
                         y = mean,
                         colour = interaction(genotype, sex))) + 
  geom_point() +
  geom_line(aes(y = predictMorphineLME, 
                group = interaction(genotype, sex))) +
  facet_grid(~treatment)

plot(factor(morphineData$genotype), morphineData$mean)

```


```{r}
#separating morphine and saline responses
morphineData_latencysep <- morphineData %>%
  rename(mean_latency = mean) %>%
  group_by(ID, sex, genotype, timepoint) %>%
  mutate(morphine_latency = mean_latency[treatment== "morphine"],
         saline_latency = mean_latency[treatment == "saline"]) %>%
  ungroup()

salineCoVmorphine <- lmer(log(morphine_latency) ~  genotype * sex * factor(timepoint) + (1|ID) + log(saline_latency), data = morphineData_latencysep)

summary(salineCoVmorphine) 
plot(salineCoVmorphine)
Anova(salineCoVmorphine)
qqnorm(resid(salineCoVmorphine))
qqline(resid(salineCoVmorphine))



emmeans(salineCoVmorphine, pairwise ~ sex * genotype | factor(timepoint))

```

